import { QueueStatus } from '../model/enums.mjs';
import { BRAND } from '../brand.mjs';

/**
 * GitHub mirror (Phase 2). Pure mapping between a review-queue candidate and a
 * GitHub issue, so the operator can approve/reject from their phone. Issue
 * creation itself is performed by the agent runtime via the GitHub MCP — this
 * module builds the payloads and maps labels back to queue transitions.
 */

const money = (m) => '$' + Math.round((m || 0) / 100).toLocaleString('en-US');

export function labelsFor(candidate) {
  return ['eclipse:candidate', `kind:${candidate.kind}`, `status:${candidate.status}`];
}

export function issueTitleFor(candidate) {
  return `[${BRAND.name} candidate] ${candidate.title}`;
}

export function issueBodyFor(candidate) {
  const c = candidate;
  const links =
    (c.sourceLinks || []).map((l) => `- [${l.label}](${l.url}) _(${l.kind})_`).join('\n') || '_none_';
  const imagery =
    (c.imagery || [])
      .map((m) => `- \`${m.role}\`: ${m.url} ${m.approved ? '(approved)' : '(pending approval)'}`)
      .join('\n') || '_none_';
  const gate = c.gate?.passed ? '✅ gate pass' : `⛔ gate blocked — ${(c.gate?.blockers || []).join(', ')}`;

  return [
    c.summary ? `> ${c.summary}` : '',
    '',
    '| field | value |',
    '|---|---|',
    `| candidate | \`${c.id}\` |`,
    `| kind | ${c.kind} |`,
    `| status | ${c.status} |`,
    `| suggested price | ${money(c.costs?.suggestedListMinor)} |`,
    `| unit cost | ${money(c.costs?.unitCostMinor)} |`,
    `| margin | ${c.costs?.marginPct || 0}% |`,
    `| readiness | ${c.scores?.readiness || 0} / 100 |`,
    `| gate | ${gate} |`,
    '',
    '### Source links (review before approving)',
    links,
    '',
    '### Imagery',
    imagery,
    '',
    '### Decide',
    '- **Approve** → add the `approve` label. An operator publish step then takes it live.',
    '- **Request changes** → add the `needs-changes` label with a comment.',
    '- **Reject** → add the `reject` label.',
    '',
    `_Nothing goes live until a human approves. Generated by ${BRAND.display}._`,
  ].join('\n');
}

export function issuePayloadFor(candidate) {
  return {
    title: issueTitleFor(candidate),
    body: issueBodyFor(candidate),
    labels: labelsFor(candidate),
  };
}

/** Label → intended queue target, for pulling decisions back from GitHub. */
export const LABEL_TRANSITIONS = Object.freeze({
  approve: QueueStatus.APPROVED,
  approved: QueueStatus.APPROVED,
  reject: QueueStatus.REJECTED,
  rejected: QueueStatus.REJECTED,
  'needs-changes': QueueStatus.NEEDS_CHANGES,
});

export function transitionForLabels(labels = []) {
  for (const l of labels) {
    const key = String(l).toLowerCase();
    if (LABEL_TRANSITIONS[key]) return LABEL_TRANSITIONS[key];
  }
  return null;
}
