import { QueueStatus } from '../model/enums.mjs';
import { BRAND } from '../brand.mjs';

/**
 * GitHub mirror (Phase 2). Pure mapping between a review-queue candidate and a
 * GitHub issue, so the operator can approve/reject from their phone. Issue
 * creation itself is performed by the agent runtime via the GitHub MCP — this
 * module builds the payloads and maps labels back to queue transitions.
 */

const money = (m) => '$' + Math.round((m || 0) / 100).toLocaleString('en-US');

/** Escape characters that would break a Markdown table cell or body. */
const mdCell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/[\r\n]+/g, ' ');

export function labelsFor(candidate) {
  return ['eclipse:candidate', `kind:${candidate.kind}`, `status:${candidate.status}`];
}

export function issueTitleFor(candidate) {
  return `[${BRAND.name} candidate] ${candidate.title}`;
}

export function issueBodyFor(candidate) {
  const c = candidate;
  const links =
    (c.sourceLinks || []).map((l) => `- [${mdCell(l.label)}](${l.url}) _(${mdCell(l.kind)})_`).join('\n') || '_none_';
  const imagery =
    (c.imagery || [])
      .map((m) => `- \`${m.role}\`: ${m.url} ${m.approved ? '(approved)' : '(pending approval)'}`)
      .join('\n') || '_none_';
  const gate = c.gate?.passed ? '✅ gate pass' : `⛔ gate blocked — ${(c.gate?.blockers || []).join(', ')}`;

  return [
    c.summary ? `> ${mdCell(c.summary)}` : '',
    '',
    '| field | value |',
    '|---|---|',
    `| candidate | \`${c.id}\` |`,
    `| kind | ${mdCell(c.kind)} |`,
    `| status | ${mdCell(c.status)} |`,
    `| suggested price | ${money(c.costs?.suggestedListMinor)} |`,
    `| unit cost | ${money(c.costs?.unitCostMinor)} |`,
    `| margin | ${c.costs?.marginPct || 0}% |`,
    `| readiness | ${c.scores?.readiness || 0} / 100 |`,
    `| gate | ${gate} |`,
    '',
    '### Source links (review before approving)',
    links,
    '',
    '### Imagery',
    imagery,
    '',
    '### Decide',
    '- **Approve** → add the `approve` label. An operator publish step then takes it live.',
    '- **Request changes** → add the `needs-changes` label with a comment.',
    '- **Reject** → add the `reject` label.',
    '',
    `_Nothing goes live until a human approves. Generated by ${BRAND.display}._`,
  ].join('\n');
}

export function issuePayloadFor(candidate) {
  return {
    title: issueTitleFor(candidate),
    body: issueBodyFor(candidate),
    labels: labelsFor(candidate),
  };
}

/** Label → intended queue target, for pulling decisions back from GitHub. */
export const LABEL_TRANSITIONS = Object.freeze({
  approve: QueueStatus.APPROVED,
  approved: QueueStatus.APPROVED,
  reject: QueueStatus.REJECTED,
  rejected: QueueStatus.REJECTED,
  'needs-changes': QueueStatus.NEEDS_CHANGES,
});

/**
 * Map an issue's labels to a queue transition. When labels conflict, the most
 * conservative action wins (reject > needs-changes > approve) — safe-by-default:
 * a candidate is never approved just because an "approve" label sits alongside
 * a "reject" or "needs-changes".
 */
export function transitionForLabels(labels = []) {
  const keys = new Set(labels.map((l) => String(l).toLowerCase()));
  if (keys.has('reject') || keys.has('rejected')) return QueueStatus.REJECTED;
  if (keys.has('needs-changes')) return QueueStatus.NEEDS_CHANGES;
  if (keys.has('approve') || keys.has('approved')) return QueueStatus.APPROVED;
  return null;
}
