import type { ProductCandidate, VendorId } from './curation';
import { attachReview } from './curation';

const now = () => new Date().toISOString();

export function fixtureCandidates(vendor: VendorId = 'manual'): ProductCandidate[] {
  const ts = now();
  return [
    attachReview({
      id: `${vendor}-modular-carryall`,
      vendor,
      supplier_id: `${vendor}-supplier-01`,
      supplier_name: vendor === 'manual' ? 'Manual Supplier Intake' : `${vendor.toUpperCase()} configured feed`,
      supplier_sku: 'LUM-CARRY-001',
      title: 'Modular Carryall System',
      description: 'Structured everyday carry with removable interior organizers, water-resistant shell, and low-profile hardware.',
      handle: 'modular-carryall-system',
      category: 'bags and travel accessories',
      category_tree: ['accessories', 'bags', 'travel'],
      chapter: 'armor',
      source_url: 'https://lumera.local/vendor-fixture/modular-carryall-system',
      image_url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80',
      media_rights: vendor === 'manual' ? 'unknown' : 'supplier_license',
      brand_risk: 'low',
      quality_risk: 'known',
      counterfeit_risk: 'low',
      recalled_risk: 'low',
      regulated_risk: 'low',
      supplier_reliability: vendor === 'manual' ? 68 : 84,
      demand_score: 84,
      brand_fit_score: 91,
      novelty_score: 77,
      return_risk_score: 28,
      lead_time_days: 9,
      warehouse_region: 'US/EU blended',
      cost_cents: 3400,
      retail_cents: 7900,
      stock: 190,
      variants: [
        {
          sku: 'LUM-CARRY-001-BLK',
          title: 'Black / Standard',
          supplier_sku: 'LUM-CARRY-001-BLK',
          option_values: { Color: 'Black', Size: 'Standard' },
          cost_cents: 3400,
          retail_cents: 7900,
          stock: 90,
        },
        {
          sku: 'LUM-CARRY-001-STN',
          title: 'Stone / Standard',
          supplier_sku: 'LUM-CARRY-001-STN',
          option_values: { Color: 'Stone', Size: 'Standard' },
          cost_cents: 3400,
          retail_cents: 7900,
          stock: 100,
        },
      ],
      reasons: ['High utility with premium positioning', 'Strong bundle potential', 'Fits Armor chapter without fragile sizing risk'],
      created_at: ts,
      updated_at: ts,
      status: 'ingested',
    }),
    attachReview({
      id: `${vendor}-atelier-desk-lamp`,
      vendor,
      supplier_id: `${vendor}-supplier-02`,
      supplier_name: vendor === 'manual' ? 'Manual Supplier Intake' : `${vendor.toUpperCase()} configured feed`,
      supplier_sku: 'LUM-LAMP-014',
      title: 'Atelier Desk Lamp',
      description: 'Compact aluminum desk lamp with warm dimming, weighted base, and a sculptural task-light profile.',
      handle: 'atelier-desk-lamp',
      category: 'home office lighting',
      category_tree: ['home', 'office', 'lighting'],
      chapter: 'signal',
      source_url: 'https://lumera.local/vendor-fixture/atelier-desk-lamp',
      image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80',
      media_rights: 'unknown',
      brand_risk: 'medium',
      quality_risk: 'unknown',
      counterfeit_risk: 'low',
      recalled_risk: 'unknown',
      regulated_risk: 'medium',
      supplier_reliability: 72,
      demand_score: 79,
      brand_fit_score: 88,
      novelty_score: 71,
      return_risk_score: 33,
      lead_time_days: 15,
      warehouse_region: 'CN/US warehouse pending',
      cost_cents: 2200,
      retail_cents: 5400,
      stock: 120,
      variants: [
        {
          sku: 'LUM-LAMP-014-BLK',
          title: 'Black',
          supplier_sku: 'LUM-LAMP-014-BLK',
          option_values: { Color: 'Black' },
          cost_cents: 2200,
          retail_cents: 5400,
          stock: 120,
        },
      ],
      reasons: ['Strong visual fit for Signal chapter', 'Potentially high AOV home-office add-on', 'Needs certification and media verification before launch'],
      created_at: ts,
      updated_at: ts,
      status: 'ingested',
    }),
    attachReview({
      id: `${vendor}-founder-heavyweight-tee`,
      vendor: vendor === 'manual' ? 'printify' : vendor,
      supplier_id: 'pod-studio-01',
      supplier_name: 'POD Studio Intake',
      supplier_sku: 'LUM-TEE-ALTAR-001',
      title: 'ALTER Heavyweight Studio Tee',
      description: 'Founder-designed heavyweight cotton tee with minimal front mark and back-print art for ALTER house-label drops.',
      handle: 'alter-heavyweight-studio-tee',
      category: 'apparel tee',
      category_tree: ['apparel', 'tops', 'tee'],
      chapter: 'altar',
      source_url: 'https://lumera.local/vendor-fixture/alter-heavyweight-studio-tee',
      image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
      media_rights: 'supplier_license',
      brand_risk: 'low',
      quality_risk: 'unknown',
      counterfeit_risk: 'low',
      recalled_risk: 'low',
      regulated_risk: 'low',
      supplier_reliability: 92,
      demand_score: 94,
      brand_fit_score: 95,
      novelty_score: 83,
      return_risk_score: 46,
      lead_time_days: 5,
      warehouse_region: 'US POD',
      cost_cents: 1850,
      retail_cents: 4900,
      stock: 999,
      variants: ['S', 'M', 'L', 'XL', '2XL'].map((size) => ({
        sku: `LUM-TEE-ALTAR-001-${size}`,
        title: `Black / ${size}`,
        supplier_sku: `LUM-TEE-ALTAR-001-${size}`,
        option_values: { Color: 'Black', Size: size },
        cost_cents: 1850,
        retail_cents: 4900,
        stock: 199,
      })),
      reasons: ['Founder product studio lane', 'High brand fit', 'Sample recommended before scaling apparel'],
      created_at: ts,
      updated_at: ts,
      status: 'ingested',
    }),
  ];
}
